### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by not-matthias** [htl-perg-2019-20-5ahif/docker-wpf-exercise-not-matthias#1]
Here's the link to the published docker image: `https://hub.docker.com/r/notmatthias/carbookingapi`.

I was unfortunately not able to run it via the command line. Neither `docker run ...` nor `docker-compose up` did work. I somehow couldn't login. 

It worked fine when I ran it in Visual Studio. Not sure what's causing this to fail.

**Comment by rstropek** [comment]
Hi @not-matthias!

I took a look at your homework. I think the following error message of your Dockerized API is a hint to the root cause of your problem: *System.IO.FileNotFoundException: Could not find file '/app/Import.sql'*. You did not include */app/Import.sql* into your published .NET app.

My tip: Put *Import.sql* into your DLL's resources and read it from there. Take a look at [this Stackoverflow post](https://stackoverflow.com/a/41106851). It contains hints for how to do that.

Fix that issue and the extra points belong to you.

Greetings,
Rainer Stropek.

**Comment by not-matthias** [comment]
My bad. I forgot to test the API, when I added the import script. I updated my solution and it should work now. The image is again available here: `https://hub.docker.com/r/notmatthias/carbookingapi`

[Here](https://privatebin.net/?2ba679a6b9bff5a2#FjANJUi6qWDNzjHjJQAe2AaGae7F9m2vxQ8BKwkazJx2) is the output of the `docker-compose up` command. It says that `The server was not found or was not accessible.`, but it's   working fine when I run it via Visual Studio. I have absolutely no idea what's causing this to fail.
